-- Secondary indexes for moltrack schema to support foreign
-- Comments for the moltrack schema.

-- Users
CREATE UNIQUE INDEX ON moltrack.users (email);

-- Properties
CREATE INDEX ON moltrack.properties (name);

CREATE INDEX ON moltrack.properties (value_type);

CREATE INDEX ON moltrack.properties (semantic_type_id);

CREATE INDEX ON moltrack.properties (property_class);

-- Synonym types
CREATE UNIQUE INDEX ON moltrack.synonym_types (synonym_level, name);

-- Compounds
CREATE INDEX ON moltrack.compounds (canonical_smiles);

CREATE INDEX ON moltrack.compounds (inchi);

CREATE INDEX ON moltrack.compounds (inchikey);

CREATE INDEX ON moltrack.compounds (formula);

CREATE UNIQUE INDEX ON moltrack.compounds (hash_mol);

CREATE UNIQUE INDEX ON moltrack.compounds (hash_tautomer);

CREATE UNIQUE INDEX ON moltrack.compounds (hash_canonical_smiles);

CREATE UNIQUE INDEX ON moltrack.compounds (hash_no_stereo_smiles);

CREATE UNIQUE INDEX ON moltrack.compounds (hash_no_stereo_tautomer);

CREATE UNIQUE INDEX ON moltrack.compounds (molregno);

-- Compound synonyms
CREATE INDEX ON moltrack.compound_synonyms (compound_id);

CREATE INDEX ON moltrack.compound_synonyms (synonym_type_id);

-- Compound details
CREATE INDEX ON moltrack.compound_details (compound_id);

CREATE INDEX ON moltrack.compound_details (property_id);

-- Additions
CREATE INDEX ON moltrack.additions (name);

CREATE INDEX ON moltrack.additions (code);

CREATE INDEX ON moltrack.additions (formula);

CREATE INDEX ON moltrack.additions (role);

-- Batches
CREATE INDEX ON moltrack.batches (compound_id);

CREATE INDEX ON moltrack.batches (batch_regno);

-- Batch details
CREATE INDEX ON moltrack.batch_details (batch_id);

CREATE INDEX ON moltrack.batch_details (property_id);

-- Batch synonyms
CREATE INDEX ON moltrack.batch_synonyms (batch_id);

CREATE INDEX ON moltrack.batch_synonyms (synonym_type_id);

-- Assay types
CREATE UNIQUE INDEX ON moltrack.assay_type_details (assay_type_id, property_id);

-- Assay details
CREATE UNIQUE INDEX ON moltrack.assay_details (assay_id, property_id);

-- Assay results
CREATE INDEX ON moltrack.assay_results (batch_id);

CREATE INDEX ON moltrack.assay_results (assay_id);

CREATE INDEX ON moltrack.assay_results (property_id);

-- Comments for the moltrack schema.

-- Users
COMMENT ON TABLE moltrack.users IS 'for MVP, just a single global user will be configured
';

-- Semantic types
COMMENT ON COLUMN moltrack.semantic_types.name IS 'e.g., Molecule, Cell, ...';

-- Properties
COMMENT ON TABLE moltrack.properties IS 'for validity checking should we have field to specify what entity this should be relevant
future: property should have ontology reference
';

COMMENT ON COLUMN moltrack.properties.value_type IS '(''int'', ''double'', ''bool'', ''datetime'', ''string'')';

COMMENT ON COLUMN moltrack.properties.property_class IS '(''CALCULATED'', ''MEASURED'', ''PREDICTED'')';

COMMENT ON COLUMN moltrack.properties.unit IS 'future: unit should point to unit ontology';

-- Settings
COMMENT ON TABLE moltrack.settings IS 'This table is used to store configuration settings for the application.
examples include:
- compound standardization rules
- compound uniqueness rules
- compound identification rules and synonym generation rules
- batch identification rules and synonym generation rules
I suspect that there should be some more structure to this table, but for MVP, this will be used to store the rules for the global user.
';

-- Synonym types
COMMENT ON TABLE moltrack.synonym_types IS 'how to address combined uniqueness constraint';

COMMENT ON COLUMN moltrack.synonym_types.synonym_level IS '(''BATCH'',''COMPOUND'')';

COMMENT ON COLUMN moltrack.synonym_types.name IS 'e.g., CAS, USAN, INN, tradename ,source code';

COMMENT ON COLUMN moltrack.synonym_types.pattern IS 'regex for identifier: CHEMBL.*';

-- Compounds
COMMENT ON COLUMN moltrack.compounds.canonical_smiles IS 'RDKit canonical SMILES';

COMMENT ON COLUMN moltrack.compounds.original_molfile IS 'as sketched by the chemist';

COMMENT ON COLUMN moltrack.compounds.molregno IS 'generated by the system based on business rules';

COMMENT ON COLUMN moltrack.compounds.inchi IS 'IUPAC InChI';

COMMENT ON COLUMN moltrack.compounds.inchikey IS 'IUPAC InChIKey';

COMMENT ON TABLE moltrack.compound_details IS 'future: compound_details.value_string should have optional ontology reference';

COMMENT ON COLUMN moltrack.compound_details.value_datetime IS 'with time zone';

-- Additions
COMMENT ON TABLE moltrack.additions IS '- Leave to admin to maintain uniqueness.
Questions:
- should we do check constraints for role?
- in the future can add roles for reagents, solvents, etc.
';

COMMENT ON COLUMN moltrack.additions.name IS 'ex. HCl';

COMMENT ON COLUMN moltrack.additions.description IS 'ex. Hydrochloric acid';

COMMENT ON COLUMN moltrack.additions.code IS 'shorthand, ex. AAC';

COMMENT ON COLUMN moltrack.additions.is_active IS 'allows for soft delete';

COMMENT ON COLUMN moltrack.additions.formula IS 'ex. HCl';

COMMENT ON COLUMN moltrack.additions.molecular_weight IS 'ex. 36.46';

COMMENT ON COLUMN moltrack.additions.smiles IS 'ex. ClH';

COMMENT ON COLUMN moltrack.additions.role IS '(''SALT'', ''SOLVATE'')';

-- Batches
COMMENT ON TABLE moltrack.batches IS 'amount, amount_unit, purity could all be added to properties';

COMMENT ON COLUMN moltrack.batches.batch_regno IS 'generated by the system based on business rules';

-- Batch additions
COMMENT ON TABLE moltrack.batch_additions IS 'This allows us to have multiple salt and solvates for a given batch''
';

COMMENT ON COLUMN moltrack.batch_additions.addition_equivalent IS 'equivalent relative to parent batch';

-- Batch details
COMMENT ON TABLE moltrack.batch_details IS 'future: batch_details.value_string should have optional ontology reference';

COMMENT ON COLUMN moltrack.batch_details.value_datetime IS 'with time zone';

-- Assay type details
COMMENT ON TABLE moltrack.assay_type_details IS 'PK: (assay_type_id, property_id)';

COMMENT ON COLUMN moltrack.assay_type_details.value_datetime IS 'timestamp with time zone';

-- Assays
COMMENT ON COLUMN moltrack.assays.name IS 'e.g., Kinase Inhibition Assay';

-- Assay details
COMMENT ON TABLE moltrack.assay_details IS 'PK: (assay_id, property_id)';

COMMENT ON COLUMN moltrack.assay_details.value_datetime IS 'with time zone';

-- Assay type properties
COMMENT ON TABLE moltrack.assay_type_properties IS 'A set of measurement types for a given assay type.
This will be used to validate the data submitted for an assay.
';

COMMENT ON COLUMN moltrack.assay_type_properties.required IS 'if true, must exist in submitted data for validation';

-- Assay results
COMMENT ON TABLE moltrack.assay_results IS 'For performance reasons, only numbers, strings, and booleans are supported for assay results (no datetime or uuid).';

COMMENT ON COLUMN moltrack.assay_results.value_qualifier IS 'SMALLINT, 0 for =, 1 for <, 2 for >. Only used for numeric properties.';

-- API keys

CREATE UNIQUE INDEX ON moltrack.api_keys(prefix);
CREATE INDEX ON moltrack.api_keys(status);